// "use server";//USE SERVER CAN ONLY EXPORT ASYNC FUNCTION
import React from 'react';
import type { Metadata } from 'next';
import styles from "./blogs.module.css";

export const metadata: Metadata = {
    title: {
        default: "ablogroom Blogs",
        template: `%s | ablogroom Blog`
    },
    description: ' Free Blogs by ABLOGROOM -Blogs Creation by Bloggers for You. It provides templates that the user can use to become an effective blogger.',
    generator: "ablogroom using Next.js",
    referrer: "origin-when-cross-origin",
    keywords: ["The Blog Room, Free to use", "blogs for you", "web info", "free blog posts", " The World is Your Oyster", " Create Your Own Blog", "Gary's Blogs"],
    authors: [{ name: "Gary Wallace", url: "https://www.masterconnect.ca" }],

    openGraph: {
        title: "ablogroom",
        description: 'Generated by www.masterconnect.ca,tools for you',
        url: "https://www.ablogroom.com",
        siteName: "ablogroom",
        images: [
            {
                url: "/images/favicon-192x192.png",
                width: 192,
                height: 192
            },
            {
                url: "https://www.ablogroom.com/images/thankYou.png",
                width: 600,
                height: 900
            },
            {
                url: "/images/favicon-512x512.png",
                width: 512,
                height: 512
            },

        ],
    },

}


type Props = {
    params: { id: string }
    searchParams: { [key: string]: string | string[] | undefined }
}


export default function blogslayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className={styles.blogLayout}>
            <div className={styles.blogLayoutInner}>
                {children}
            </div>
        </div>
    )
}