import type { Metadata } from "next";
import { Geist, Geist_Mono, Playwrite_AR } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const playwrite = Playwrite_AR({
  variable: "--Playwrite",

})

export const metadata: Metadata = {
  metadataBase: new URL("https://www.ablogroom.com"),
  alternates: {
    canonical: '/bio',
    languages: {
      'en-US': '/en-US',
      'fr-CA': '/fr-CA',
    },
  },
  title: {
    default: "Resume Builder",
    template: `%s | Resume Builder`,

  },
  category: "resume",
  description: 'Resume Builder',
  generator: "Next.js",
  applicationName: "Resume Builder",
  referrer: "origin-when-cross-origin",
  keywords: ["Build Your resume, Free to use", "References", "Cover Letter", "Resume Builder", " Professionally Done", " Simple to use, Resume Builder", "Free for all"],
  authors: [{ name: "Gary Wallace", url: "https://www.masterconnect.ca" }],
  // colorScheme:"light",
  creator: "Gary Wallace",
  publisher: "Gary Wallace",
  formatDetection: {
    email: true,
    address: false,
    telephone: true
  },
  openGraph: {
    title: "Resume Builder",
    description: 'Generated by www.masterconnect.ca,tools for you',
    url: "https://www.ablogroom.com",
    siteName: "ablogroom",
    images: [
      {
        url: "https://newablogroom-free-bucket.s3.us-east-1.amazonaws.com/resumeBuilder600x433.png",
        width: 600,
        height: 433
      },
      {
        url: "https://new-master.s3.ca-central-1.amazonaws.com/ablogroom/gb_logo_600.png",
        width: 600,
        height: 600
      },

      {
        url: "https://new-master.s3.ca-central-1.amazonaws.com/ablogroom/thankYou.png",
        width: 600,
        height: 900
      },
    ],
    locale: "en-CA",
    type: "website"

  },


};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`${geistSans.variable} ${geistMono.variable} ${playwrite.variable}`}>
      {children}
    </main>
  );
}
