// "use server"; //EXPORTS ONLY ASYNC FUNCTIONS
import React from 'react';
import type { Metadata, ResolvingMetadata } from 'next';
import styles from "@/components/posts/post.module.css";
import { PrismaClient } from "@prisma/client";
// import { postType, userType } from '@/components/editor/Types';
// import { awsImage } from '@/lib/awsFunctions';
// const prisma = new PrismaClient();

export const metadata: Metadata = {
    title: {
        default: "ablogroom Posts",
        template: `%s | "ablogroom Posts"}`,

    },
    description: ' Free Posts && Blogs by ABLOGROOM -Blogs Creation by Bloggers for You. It provides templates that the user can use to become an effective blogger.',
    generator: "ablogroom using Next.js",
    referrer: "origin-when-cross-origin",
    keywords: ["MUST SEE!", "The Blog Room Posts, Free to use", "blogs/Posts for you", "web info", "free blog-posts", " The World is Your Oyster", " Create Your Own Blog", "Create a Post"],
    authors: [{ name: "Gary Wallace", url: "https://www.masterconnect.ca" }],
    openGraph: {
        title: "ablogroom",
        description: 'Generated by www.masterconnect.ca,tools for you',
        url: "https://www.ablogroom.com",
        siteName: "ablogroom",
        images: [
            {
                url: "/images/gb_logo.png",
            },
            {
                url: "https://new-master.s3.ca-central-1.amazonaws.com/static/masterultils/masterUltils800_400.png",
            },
        ],

    }

}



export default async function postlayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className={styles.layoutposts}>
            {children}
        </div>
    )
}



// export async function generateMetdata(parent: ResolvingMetadata): Promise<Metadata> {
//     const meta_ = await retPostsMetadata({ parent });
//     console.log("GENERATEMETADATA", meta_);
//     return meta_;
// }
// export async function retPostsMetadata(item: { parent: ResolvingMetadata }): Promise<Metadata> {
//     const { parent } = item;
//     const par = await parent ? await parent : undefined;
//     const url = par && par.metadataBase ? par.metadataBase.origin : "https://www.ablogroom.com";
//     const initKeywords = ["POSTS !MUST SEE!!", "The Blog Room, Free to use", "blogs for you", "web info", "free blog posts", " The World is Your Oyster", " Create Your Own Blog", "Gary's Blogs"];
//     const posts = await prisma.post.findMany({ where: { published: true }, select: { title: true, content: true, imageKey: true } }) as postType[];
//     const images = (posts && posts.length > 0) ? await Promise.all(posts.slice(0, 2).map(async (post) => ({ url: post.imageKey ? await awsImage(post.imageKey) : "/images/gb_logo.png" }))) : [];
//     const keywords = (posts && posts.length > 0) ? posts.map(post => (post.title)) : [];
//     const initImgs: { url: string }[] = [
//         {
//             url: "/images/gb_logo.png"
//         },
//         {
//             url: "https://new-master.s3.ca-central-1.amazonaws.com/static/masterultils/masterUltils800_400.png"
//         },
//     ];
//     const initAuthors = [{ name: "Gary Wallace", url: "https://www.masterconnect.ca" }]

//     const metaReturn: Metadata = {
//         title: {
//             default: "ablogroom Posts",
//             template: `%s | "ablogroom Posts"}`,

//         },

//         description: ' Free Blogs by ABLOGROOM -Blogs Creation by Bloggers for You. It provides templates that the user can use to become an effective blogger.',
//         generator: "ablogroom using Next.js",
//         referrer: "origin-when-cross-origin",
//         keywords: keywords ? keywords.concat(initKeywords) : initKeywords,
//         authors: initAuthors,
//         // colorScheme:"light",
//         openGraph: {
//             title: "ablogroom",
//             description: 'Generated by www.masterconnect.ca,tools for you',
//             url: url,
//             siteName: "ablogroom",
//             images: images ? images.concat(initImgs) : initImgs,

//         },

//     }
//     return metaReturn;
// }