// "use server"; //EXPORTS ONLY ASYNC FUNCTIONS
import React from 'react';
import type { Metadata, ResolvingMetadata } from 'next';
import styles from "@/components/posts/post.module.css";

export const metadata: Metadata = {
    title: {
        default: "ablogroom Posts",
        template: `%s | "ablogroom Posts"}`,

    },
    description: ' Free Posts && Blogs by ABLOGROOM -Blogs Creation by Bloggers for You. It provides templates that the user can use to become an effective blogger.',
    generator: "ablogroom using Next.js",
    referrer: "origin-when-cross-origin",
    keywords: ["MUST SEE!", "The Blog Room Posts, Free to use", "blogs/Posts for you", "web info", "free blog-posts", " The World is Your Oyster", " Create Your Own Blog", "Create a Post"],
    authors: [{ name: "Gary Wallace", url: "https://www.masterconnect.ca" }],
    openGraph: {
        title: "ablogroom",
        description: 'Generated by www.masterconnect.ca,tools for you',
        url: "https://www.ablogroom.com",
        siteName: "ablogroom",
        images: [
            {
                url: "https://www.ablogroom.com/images/posts.png",
                width: 600,
                height: 600
            },
            {
                url: "https://www.ablogroom.com/images/bg_logo_600.png",
                width: 600,
                height: 600
            },
            {
                url: "https://new-master.s3.ca-central-1.amazonaws.com/static/masterultils/masterUltils800_400.png",
            },
        ],

    }

}



export default async function postlayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className={styles.layoutposts}>
            {children}
        </div>
    )
}
